// Generated by scripts/update-catalog.py
window.PELICAN_MODELS = [
  {
    "name": "amazon",
    "file": "animations/amazon.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "bytedance-seed",
    "file": "animations/bytedance-seed.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "DeepSeek4.1",
    "file": "animations/DeepSeek4.1.html",
    "tech": [
      "SVG",
      "CSS 动画",
      "SMIL"
    ]
  },
  {
    "name": "fable5.1",
    "file": "animations/fable5.1.html",
    "tech": [
      "SVG",
      "CSS 动画",
      "JavaScript 动画"
    ]
  },
  {
    "name": "fable5",
    "file": "animations/fable5.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "GLM5.3",
    "file": "animations/GLM5.3.html",
    "tech": [
      "SVG",
      "CSS 动画",
      "SMIL"
    ]
  },
  {
    "name": "Google-gemini3.8",
    "file": "animations/Google-gemini3.8.html",
    "tech": [
      "SVG",
      "CSS 动画",
      "JavaScript 动画"
    ]
  },
  {
    "name": "grok4.6",
    "file": "animations/grok4.6.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "IBM-Granite",
    "file": "animations/IBM-Granite.html",
    "tech": [
      "SVG",
      "SMIL"
    ]
  },
  {
    "name": "k3",
    "file": "animations/k3.html",
    "tech": [
      "SVG",
      "CSS 动画",
      "SMIL"
    ]
  },
  {
    "name": "meta-muse1.6",
    "file": "animations/meta-muse1.6.html",
    "tech": [
      "SVG",
      "CSS 动画",
      "SMIL",
      "JavaScript 动画"
    ]
  },
  {
    "name": "mimo2.5",
    "file": "animations/mimo2.5.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "mistrial",
    "file": "animations/mistrial.html",
    "tech": [
      "SVG",
      "SMIL"
    ]
  },
  {
    "name": "Nvidia-Nemotron",
    "file": "animations/Nvidia-Nemotron.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "openpangu2",
    "file": "animations/openpangu2.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "opus4.8",
    "file": "animations/opus4.8.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "opus5",
    "file": "animations/opus5.html",
    "tech": [
      "SVG",
      "CSS 动画",
      "JavaScript 动画"
    ]
  },
  {
    "name": "Poolside",
    "file": "animations/Poolside.html",
    "tech": [
      "CSS 动画"
    ]
  },
  {
    "name": "Qwen3.7max",
    "file": "animations/Qwen3.7max.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "Qwen3.8max",
    "file": "animations/Qwen3.8max.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "Tencent-hy3",
    "file": "animations/Tencent-hy3.html",
    "tech": [
      "SVG",
      "CSS 动画"
    ]
  },
  {
    "name": "Tencent-hy4",
    "file": "animations/Tencent-hy4.html",
    "tech": [
      "SVG",
      "CSS 动画",
      "SMIL"
    ]
  }
];
