#!/usr/bin/env python3
"""Refresh the local preview catalog without changing original artworks."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
alias_file = root / 'data' / 'animation-aliases.json'
aliases = json.loads(alias_file.read_text(encoding='utf-8')) if alias_file.exists() else {}
models = []
for path in sorted((root / 'animations').glob('*.html'), key=lambda path: path.name.casefold()):
    source = path.read_text(encoding='utf-8')
    tech = []
    if re.search(r'<svg\b', source, re.I):
        tech.append('SVG')
    if re.search(r'<canvas\b', source, re.I):
        tech.append('Canvas')
    if '@keyframes' in source:
        tech.append('CSS 动画')
    if re.search(r'<animate(?:Transform|Motion)?\b', source):
        tech.append('SMIL')
    if 'requestAnimationFrame' in source:
        tech.append('JavaScript 动画')
    file = path.relative_to(root).as_posix()
    previous_names = [old for old, current in aliases.items() if current == file]
    legacy_aliases = list(dict.fromkeys(previous_names + [Path(old).name for old in previous_names]))
    models.append({'name': path.stem, 'file': file, 'aliases': legacy_aliases, 'tech': tech or ['HTML']})
output = root / 'data' / 'generated' / 'models.js'
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text(
    '// Generated by scripts/update-catalog.py\nwindow.PELICAN_MODELS = '
    + json.dumps(models, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Updated data/generated/models.js: {len(models)} versions')
